spring:
  application:
    name: service-module
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://oomall-mysql:3306/oomall?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8&autoReconnect=true
    username: oomall_user
    password: javaee_3-6
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10

server:
  port: 8081

logging:
  level:
    com.group3_6.service: INFO
  file:
    name: /app/logs/service.log

management:
  endpoints:
    web:
      exposure:
        include: health,info